modLoader="javafml"
loaderVersion="${forgeLoaderRange}"
license="MIT"
issueTrackerURL="https://github.com/TonimatasDEV/KrystalCraft/issues"

[[mods]]
modId="krystalcraft"
version="${modVersion}"
displayName="KrystalCraft"
updateJSONURL="https://api.modrinth.com/updates/krystalcraft/forge_updates.json"
displayURL="https://tonimatas.dev"
logoFile="icon.png"
authors="TonimatasDEV"
description='''
Adds lots of recipes, crystals, ingots and machines to work with them, making upgradeable armor, tools, items, blocks, or even weapons.
This mod is mainly focused on mining but also have some different mechanics like special enchantments.
All you need is to craft your tool/weapon/armor in a crafting table and upgrade it with the correspondent machine and minerals for making them better.
'''

[[dependencies.krystalcraft]]
   modId="forge"
   mandatory=true
   versionRange="${forgeLoaderRange}"
   ordering="NONE"
   side="BOTH"

[[dependencies.krystalcraft]]
   modId="minecraft"
   mandatory=true
   versionRange="[${minecraftVersion}]"
   ordering="NONE"
   side="BOTH"

[[dependencies.krystalcraft]]
modId="mythlib"
mandatory=true
versionRange="[1.0.0,1.1)"
ordering="NONE"
side="BOTH"