org.gradle.jvmargs=-Xmx3G

# Mod Properties
modVersion=0.0.4.4

# Dependencies
resourcefullibVersion=3.0.0
resourcefullibRange=3.0

# To update
jeiVersion=19.8.2.99
botariumVersion=3.2.2
botariumRange=3

# Minecraft Properties
minecraftVersion=1.21

# Fabric Properties
fabricLoaderVersion=0.15.7
fabricLoaderRange=>=0.14.0
fabricApiVersion=0.102.0

# NeoForge Properties
neoforgeVersion=21.0.5-beta
neoforgeLoaderRange=0