org.gradle.jvmargs=-Xmx3G

# Mod Properties
modVersion=0.0.4.4

# Fabric Properties https://fabricmc.net/develop/
minecraftVersion=1.21.1
yarnMappings=3
loaderVersion=0.17.2
fabricVersion=0.116.5+1.21.1

# Mod Properties
# https://github.com/TechReborn/Energy
energyVersion=4.1.0
# https://modrinth.com/mod/jei
jeiVersion=19.22.1.316