org.gradle.jvmargs=-Xmx3G

# Mod Properties
modVersion=0.0.4.4

# Dependencies
architecturyVersion=3.0.11
rlMinecraftVersion=1.21
architecturyRange=3.0.0

# To update
jeiVersion=19.21.0.247

# Minecraft Properties
minecraftVersion=1.21.1

# Fabric Properties
fabricLoaderVersion=0.16.10
fabricLoaderRange=>=0.15.0
fabricApiVersion=0.115.0

# NeoForge Properties
neoforgeVersion=21.1.117
neoforgeLoaderRange=0