modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "Apache License Version 2.0"
issueTrackerURL = "https://github.com/TonimatasDEV/KrystalCraft/issues"

[[mods]]
modId = "krystalcraft"
version = "${mod_version}"
displayName = "KrystalCraft"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/krystalcraft"
logoFile = "krystalcraft.png"
credits = "Credits to Forge and IntelliJ IDEA"
authors = "TonimatasDEV [Lead] - d4niz [Artist]"
description = '''${mod_description}'''

[[dependencies.krystalcraft]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.krystalcraft]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
