modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="krystalcraft"
version="0.0.1.3"
displayName="KrystalCraft"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="examplemod.png"
#credits=""
authors="TonimatasMC [Lead] - danizml [Artist]"
description='''

'''

[[dependencies.krystalcraft]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.krystalcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
